#include "ForwardDeclaration.h"
#include "SqliteResult.h"
#include "utilities.h"
#include "ConnectSocket.h"
#include "Render.h"
#include "IGUIIconTable.h"
#include "IGUIChatBox.h"
#include "CGUIEditBox.h"
#include "CGUIButton.h"
#include "CGUIMeshViewer.h"
#include "CGUIFileOpenDialog.h"

#include "GameObject.h"
#include "MapObject.h"
#include "MapCell.h"
#include "NPC.h"
#include "Item.h"
#include "Static.h"
#include "Character.h"
#include "Quest.h"
#include "Skill.h"

#include "CurrentGameObject.h"
#include "CurrentMapObject.h"
#include "CurrentNPC.h"
#include "CurrentItem.h"
#include "CurrentStatic.h"
#include "CurrentCharacter.h"
#include "CurrentQuest.h"
#include "CurrentSkill.h"

#include "Location.h"
#include "GameResources.h"
#include "GameData.h"
#include "Game.h"
