AddNPC(1, CHARACTER_X - 1, CHARACTER_Y - 1, CHARACTER_LOCATION_ID);
AddNPC(1, CHARACTER_X - 1, CHARACTER_Y + 1, CHARACTER_LOCATION_ID);
AddNPC(1, CHARACTER_X + 1, CHARACTER_Y + 1, CHARACTER_LOCATION_ID);
AddNPC(1, CHARACTER_X + 1, CHARACTER_Y - 1, CHARACTER_LOCATION_ID);
